//! Every product constant lives here (PRODUCT.md Â§2 "Compile-time parameters").

// Generated by build.rs: PINs from SWET_PIN_CITY / SWET_PIN_SPORT and the
// version string (with "-dev" when built with the public dev PINs).
include!(concat!(env!("OUT_DIR"), "/build_info.rs"));

/// Main loop tick.
pub const TICK_MS: u32 = 20;

// --- buttons (PRODUCT Â§4) ---
/// A raw change must be seen this many ticks in a row (2 Ã 20 ms).
pub const DEBOUNCE_SAMPLES: u8 = 2;
/// Double-click window.
pub const DBL_MS: u32 = 350;
/// Hold threshold.
pub const HOLD_MS: u32 = 1000;

// --- bike ---
/// Wheel circumference.
pub const WHEEL_MM: u32 = 2165;
/// Nominal pack voltage for watts = amps Ã volts (stock firmware reports no voltage).
pub const PACK_V: u32 = 52;
pub const PAS_MAX: u8 = 9;
/// City limit; the sport PIN stores `SPORT_LIMIT_KMH` (PRODUCT Â§6).
pub const CITY_LIMIT_KMH: u8 = 25;
pub const SPORT_LIMIT_KMH: u8 = 99;

// --- persistence and power (PRODUCT Â§6, Â§8) ---
/// Save settings this long after the last change.
pub const SAVE_DEBOUNCE_MS: u32 = 3000;
/// Power off after this long with no speed, no motor current and no buttons.
pub const AUTO_OFF_MS: u32 = 5 * 60 * 1000;
/// Power-off waits at most this long for the last save to reach flash.
pub const SAVE_BEFORE_OFF_MS: u32 = 500;
/// The padlock shows this long before a lock powers off.
pub const LOCK_FLASH_MS: u32 = 500;
/// "WRONG PIN" stays on the PIN screen this long.
pub const PIN_WRONG_MS: u32 = 1500;
/// "Done" stays on a menu item this long after a confirmed action.
pub const MENU_DONE_MS: u32 = 800;
/// Distances are saved every this many meters while riding…
pub const SAVE_EVERY_M: u32 = 1000;
/// …and after standing still this long with at least `SAVE_STOPPED_MIN_M` unsaved.
pub const SAVE_STOPPED_MS: u32 = 5000;
pub const SAVE_STOPPED_MIN_M: u32 = 100;

// --- motor bus (TECH_DESIGN Â§7) ---
/// One request per slot.
pub const MOTOR_SLOT_MS: u32 = 100;
/// No valid reply for this long = link lost.
pub const MOTOR_LINK_TIMEOUT_MS: u32 = 2000;
/// Re-send walk assist (PAS 06) this often while held; 0 = only on change
/// (Swang Stodva behaviour). Set from HW probe page 7 if the controller times it out.
pub const WALK_KEEPALIVE_MS: u32 = 0;
/// A dismissed error screen comes back after this long if the fault persists.
pub const FAULT_REPEAT_MS: u32 = 10_000;
/// WRITE_SPEED_LIM unit: wheel RPM (true) or Swang Stodva's km/h Ã 10 (false).
/// Unverified on stock firmware (TECH_DESIGN Â§16).
pub const SPEED_LIMIT_AS_RPM: bool = true;
